### ISSUE TITLE
Option to ignore style issues in generated code

### ISSUE THREAD

**Issue by weswigham** [globexdesigns/brackets-jsxhint#2]
JSXHint notifies me about a bunch of problems in compiled code - most often that the compiled code uses double quotes, where my project's conventions are "quotmark": "single". I wouldn't consider these an issue since they don't impact the original source (and it's not like I can do anything about them) and would find the option to silence problems found in generated code useful.

**Comment by globexdesigns** [comment]
What is the error code for those messages? Typically JSXHint will show errors `Error description (W0000) Line of code`

W0000 in that case would be the error code.

**Comment by weswigham** [comment]
W109 (quotes) and W033 (semicolons).

**Comment by globexdesigns** [comment]
Hmm. I'm not sure which JSHint rule is used to enable those. Can you try disabling the "white" rule to see if it makes any difference?

**Comment by weswigham** [comment]
W109 is about quotemark consistency and is enabled by the "quotmark" rule which I have turned on for my project (I believe W109 is specifically for single quotes, while W108 is for double, if I'm reading the documentation correctly). W033 is enabled by default and is about automatic semicolon insertion, but can be disabled with the relaxing "asi" rule.

**Comment by globexdesigns** [comment]
Sounds like something you should report to https://github.com/jshint/jshint then. I'm not sure what I can do about this on my end.

**Comment by globexdesigns** [comment]
Hmm, unfortunately, I'm not sure if I have any control over this since all code in this extension is run through the JSX Transformer and I don't see any options in it for how to handle quotes. See: https://github.com/facebook/react/issues/445

The only suggestion I've seen (at https://github.com/STRML/JSXHint/issues/21) is to use this at the top of your file: `/* jshint quotmark:false */`
